#!/usr/bin/env zsh

silent-grub() {
    echo "Generating GRUB configuration at /boot/grub/grub.cfg ..."
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    
    echo "=> Silencing GRUB output..."	# Deletes any line that contains 'echo Loading*'
    sudo sed -i -E '/^[[:space:]]*echo[[:space:]]+'\''Loading /d' /boot/grub/grub.cfg
    
    echo "=> Done! Silent boot maintained."
}
