wallpaper {
    monitor = desc:HP Inc. HP E27 G5 CNC43529GK
    path = /home/cybervitor/Pictures/Wallpapers/space-purple-glow.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:HP Inc. HP E27 G5 CNC4352B36
    path = /home/cybervitor/Pictures/Wallpapers/tokyo-street.png
    fit_mode = cover
}

wallpaper {
	monitor = desc:HP Inc. HP E27 G5 CNC43529GS
	path = /home/cybervitor/Pictures/Wallpapers/zaku-space-glow.jpg
	fit_mode = cover
}

wallpaper {
	monitor = desc:LG Electronics LG ULTRAGEAR 509NTDVM2162
	path = /home/cybervitor/Pictures/Wallpapers/mech-hangar.jpg
	fit_mode = cover
}
