#!/usr/bin/env zsh

# Alter default behaviour
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll="eza -Gloha --no-permissions --color=always --color-scale=all --color-scale-mode=gradient --hyperlink --absolute=off"
alias cat="bat"
alias find='fd'
alias du="dust"
alias free="duf"
alias nano="micro"
alias top="btop"

# Shortcuts
alias s="kitten ssh"
alias cz="chezmoi cd"

alias tss="clear && echo '\n\n' && fastfetch && echo '\n\n' && kitty +kitten icat ~/Pictures/Wallpapers/gundam-pixel-arts.gif"
alias ff="fastfetch"
alias fff="clear && fastfetch"
alias mon="hyprctl monitors"
alias clean-paru="paru -Scc"

alias gits="cd ~/.local/gits"
alias back="cd ~/Projects/CSTAF/sigtaf/sigtaf-backend"
alias front="cd ~/Projects/CSTAF/sigtaf/sigtaf-frontend"
alias wiki="cd ~/Projects/CSTAF/handbook/handbook.wiki"
alias pm='cd ~/Documents/Work/"Software Team Documentation"'
alias es="cd ~/Projects/CSTAF/sigtaf/estatisticas"

# Quick opencode
alias oc-back="opencode /home/cybervitor/Projects/CSTAF/sigtaf/sigtaf-backend"
alias oc-front="opencode /home/cybervitor/Projects/CSTAF/sigtaf/sigtaf-frontend"
alias oc-config="opencode /home/cybervitor/.config/opencode"
alias oc-pm='opencode /home/cybervitor/Documents/Work/"Software Team Documentation"'
alias oc-es="opencode /home/cybervitor/Projects/CSTAF/sigtaf/estatisticas"

# Quick editing
alias edit-alias='chezmoi edit $ZDOTDIR/alias && chezmoi apply'
alias edit-zshrc='chezmoi edit $ZDOTDIR/.zshrc && chezmoi apply'
alias edit-zenv='chezmoi edit $ZDOTDIR/.zshenv && chezmoi apply'
alias edit-zprofile='chezmoi edit $ZDOTDIR/.zprofile && chezmoi apply'
alias edit-keybinds-zterminal='chezmoi edit $ZDOTDIR/keybinds && chezmoi apply'
alias edit-hypr-base="chezmoi edit $HYPRDIR/hyprland.lua && chezmoi apply"
alias edit-opencode="chezmoi edit /home/cybervitor/.config/opencode/opencode.jsonc && chezmoi apply"

# Cleaning home directory
alias adb='HOME="$XDG_DATA_HOME"/android adb'
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"

# Source Functions
export MARIADB_USER="root" 	# THIS IS FOR DEV MACHINE ONLY, DONT WORRY
export MARIADB_PASSWORD="sigtaf"

source $ZDOTDIR/scripts/notebook
source $ZDOTDIR/scripts/silent-update-grub
source $ZDOTDIR/scripts/start-sigtaf
source $ZDOTDIR/scripts/update-llama-cpp
source $ZDOTDIR/scripts/update-opencode
source $ZDOTDIR/scripts/update-orcaslicer

# Function Alias
alias sig-logs="docker logs -f sigtaf-backend"
