#!/usr/bin/env zsh

# --- XDG Standards ---
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# --- XDG Bin Home ---
export XDG_BIN_HOME="$HOME/.local/bin"

# --- Java & Others ---
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export NODE_REPL_HISTORY="$XDG_STATE_HOME"/node_repl_history
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export R_HISTFILE="$XDG_CONFIG_HOME/R/history"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export BUN_INSTALL="$XDG_DATA_HOME/bun"
export PIP_CACHE_DIR="$XDG_CACHE_HOME/pip"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"

export GITLIBS="$XDG_STATE_HOME/clojure/gitlibs"

# --- Go ---
export GOBIN="$XDG_BIN_HOME"
export GOPATH="$XDG_DATA_HOME"/go
# --- Android ---
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
export ANDROID_AVD_HOME=$XDG_DATA_HOME/android/avd
# --- Python ---
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/python/pythonrc.py
export PYTHON_HISTORY="$XDG_STATE_HOME"/python_history
# --- Others ---
export LLAMA_CPP_PATH="$HOME/.local/bin"
export MLFLOW_TRACKING_URI="sqlite:///${XDG_DATA_HOME:-$HOME/.local/share}/mlflow/mlflow.db"
export STORYBOOK_DISABLE_TELEMETRY=1
export SWT_LIBRARY_PATH="$XDG_DATA_HOME"/swt

# --- Personal Variables ---
export HYPRDIR="$XDG_CONFIG_HOME"/hypr # hyprland dots
source $ZDOTDIR/.api_keys_env # AI Keys

# --- CMD Specific ---
export HISTFILE="$XDG_STATE_HOME"/zsh/history
export EDITOR=micro
export VISUAL=micro

# --- Path Manipulation ---
typeset -U path PATH
path=(
  "$XDG_BIN_HOME"
  "$CARGO_HOME/bin"
  "$GOPATH/bin"
  "$BUN_INSTALL/bin"
  "$HOME/src/Odin"
  $path
)
export PATH
