#!/usr/bin/env zsh

if [[ -r "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi										# PL10k Instant Prompt

source $ZDOTDIR/historyconf				# Load ZSH Quality of Life Rules
source $ZDOTDIR/zstyleconf
fpath=($ZDOTDIR/completions $fpath) 	# Load completions

znap_source="$XDG_DATA_HOME/zsh/znap/znap.zsh"
if [[ ! -f "$znap_source" ]]; then		# Bootstrap ZSnap
	echo "Installing Znap..."
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git "$XDG_DATA_HOME/zsh/znap"
fi
source "$znap_source"

# Load ZSnap Plugins and PL10K Theme
znap source ohmyzsh/ohmyzsh lib/git lib/theme-and-appearance plugins/git
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source romkatv/powerlevel10k

if [[ -f "$ZDOTDIR/.p10k.zsh" ]]; then
    source "$ZDOTDIR/.p10k.zsh"			# Load PL10K Configs
fi

source $ZDOTDIR/my_alias
source $ZDOTDIR/my_functions			# Load aliases and functions
source $ZDOTDIR/work_alias
source $ZDOTDIR/keybinds				# Load Keybinds
source $ZDOTDIR/lazy_load_nvm 			# Lazy-loads NVM for 0ms added on terminal opening

