#!/usr/bin/env zsh

# Alter default behaviour
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll="eza -Gloha --no-permissions --color=always --color-scale=all --color-scale-mode=gradient --hyperlink --absolute=off"
alias cat="bat"
alias find='fd'
alias du="dust"
alias free="duf"
alias nano="micro"
alias top="btop"

# Shortcuts
alias s="kitten ssh"
alias cz="chezmoi cd"
alias tss="clear && echo '\n\n' && fastfetch && echo '\n\n' && kitty +kitten icat ~/Pictures/Wallpapers/gundam-pixel-arts.gif"
alias ff="fastfetch"
alias fff="clear && fastfetch"
alias mon="hyprctl monitors"
alias clean-paru="paru -Scc"
alias oc-back="opencode /home/cybervitor/Projects/CSTAF/sigtaf/sigtaf-backend"
alias oc-front="opencode /home/cybervitor/Projects/CSTAF/sigtaf/sigtaf-frontend"
alias oc-config="opencode /home/cybervitor/.config/opencode"

# Quick editing
alias edit-alias='chezmoi edit $ZDOTDIR/my_alias && chezmoi apply'
alias edit-work-alias='chezmoi edit $ZDOTDIR/work_alias && chezmoi apply'
alias edit-zshrc='chezmoi edit $ZDOTDIR/.zshrc && chezmoi apply'
alias edit-zenv='chezmoi edit $ZDOTDIR/.zshenv && chezmoi apply'
alias edit-zprofile='chezmoi edit $ZDOTDIR/.zprofile && chezmoi apply'
alias edit-keybinds-zterminal='chezmoi edit $ZDOTDIR/keybinds && chezmoi apply'
alias edit-hypr-base="chezmoi edit $HYPRDIR/hyprland.lua && chezmoi apply"
alias edit-opencode="chezmoi edit /home/cybervitor/.config/opencode/opencode.jsonc && chezmoi apply"

# Cleaning home directory
alias adb='HOME="$XDG_DATA_HOME"/android adb'
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"
