#!/usr/bin/env zsh

export MARIADB_USER="root" 			# THIS IS FOR DEV MACHINE ONLY, DONT WORRY
export MARIADB_PASSWORD="sigtaf"

# Must recieve at least one git repository path
function parallel-update-repos() {

	# Takes ALL passed arguments into a local array
	local projects=("$@")
	# check if any projects were passed by parameter
	if [ ${#projects[@]} -eq 0 ]; then
		echo "Error: No projects provided." >&2
		return 1
	fi

	# Create a unique temporary file to track global errors, =$(mktemp) would also be a good idea
	local err_file="/tmp/sigtaf_errors_$$"
	echo "Starting concurrent updates..."
	(
		for repo in "${projects[@]}"; do
		
			if [ -d "$repo" ]; then			
			{	# Wrap the git pull AND the "promise"/follow-up logic in a { } command group 
				git -C "$repo" pull --ff-only > /dev/null
				local exit_code=$?
				if [ $exit_code -eq 0 ]; then
					# Parse the git payload/trigger other scripts here
			   		echo "Success: $(basename "$repo")"
				else
			   		echo "Err: $(basename "$repo") failed" >&2
   					touch "$err_file" # Flag the error for the parent
				fi
			} & # background the WHOLE command group
			else
				echo "Directory not found: $repo" >&2
				touch "$err_file"
			fi
		done
		wait
	)
	# Check if any background workers created the error file
	if [ -f "$err_file" ]; then
		rm "$err_file" # Clean up
		echo "There was an error updating the projects!"
		return 1
	else
		echo "All projects updated!"
		return 0
	fi
}

readonly BASE_PATH="$HOME/Projects/CSTAF/sigtaf"
readonly BACKEND_PATH="$BASE_PATH/sigtaf-backend"
readonly FRONTEND_PATH="$BASE_PATH/sigtaf-frontend"

function start-sigtaf() {
	# asks for sudo perms upfront
	sudo -v

	while true
	do
		# -n for non-interactive, if cache SOMEHOW fails, this subthread fails gracefully
		sudo -n true
		sleep 60
		# kills this subprogram when it wakes up from sleep and realizes the main program isn't running anymore
		kill -0 "$$" || exit
	done 2>/dev/null &

	# Update both repositories
	echo "Updating Backend and Frontend"
	parallel-update-repos $BACKEND_PATH	$FRONTEND_PATH

	# Little cheat because I don't have docker's service on boot 
	# for faster boot times, so I give it a small nudge here
	docker &> /dev/null

	echo "Starting Frontend"
    ( cd "$FRONTEND_PATH" && npm start)
}
alias up=start-sigtaf
alias sig-logs="docker logs -f sigtaf-backend"
